#pragma once

#include "maskedmousearea/maskedmousearea.h"

#include <QColor>
#include <QDateTime>
#include <QGuiApplication>
#include <QImage>
#include <QList>
#include <QLocale>
#include <QMetaProperty>
#include <QObject>
#include <QPainter>
#include <QPoint>
#include <QQmlApplicationEngine>
#include <QQmlContext>
#include <QQuickImageProvider>
#include <QRect>
#include <QSize>
#include <QString>
#include <QTimer>
#include <QTimeZone>
#include <QTranslator>
#include <QVariant>
#include <QVector>

#include <algorithm>
#include <chrono>
#include <filesystem>
#include <fstream>
#include <functional>
#include <iostream>
#include <map>
#include <memory>
#include <mutex>
#include <queue>
#include <random>
#include <set>
#include <shared_mutex>
#include <stdexcept>
#include <string>
#include <thread>
#include <type_traits>
#include <utility>
#include <vector>
